### ISSUE TITLE
更新脚本后，不知道哪里出错导致容器不停的重启

### ISSUE THREAD

**Issue by lion-goose** [mixool/jd_sku#1]
-
![1618549907(1)](https://user-images.githubusercontent.com/59443350/114974716-80aca780-9eb5-11eb-95ad-02d977dba6f9.jpg)

**Comment by mixool** [comment]
#### 由于更新可能引入未知BUG,建议复制脚本内容至GIST使用
我的VPS上使用 没有出现这个问题
尝试修复了一下 你再试试呢

**Comment by lion-goose** [comment]
> #### 由于更新可能引入未知BUG,建议复制脚本内容至GIST使用
> 我的VPS上使用 没有出现这个问题
> 尝试修复了一下 你再试试呢

ok！恢复了！
感谢您修复
